### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by talvasconcelos** [lnbits/calendar.nostr.com#1]
General
- [x] calendar: background color -> nostr dark blue
- [x]  style for the clock
- [x] create page -> add Cancel button
- [x] Create/Edit Calendar -> add empty dropdown for identity
- [ ] Past events excluded
- [x] `minutes` instead of `m` in create/edit calendar
- [x] smaller timeslots (5, 10, 15 minutes, etc...) (maybe too granular?)
- [x] add share calendar
- [x] check jmeter tests (lnbits extension)
- [x] add fiat denomination 
- [x] notify owner of new appointment (Nostr) (lnbits/lncalendar#12)
- [x] auto respond to client on appointment paid/booked (lnbits/lncalendar#14)

Appointment List:
 - [x] scheduled at
 - [x] booked at
 - [ ] actions: cancel, move, message (nice-to-have for npubs)
     - [x] delete/cancel
     - [x] reschedule
     - [ ] message (needs a chat, or both parties message in nostr client of choice? @motorina0 ? )
 - [x] filter by selecting date range

Availability List:
- [x] no checkbox
- [x] add delete to item
- [x] give it a name
- [ ] filter by selecting date range

Payment
- [ ] service payment method
- [ ] freemium (operator takes % per appointment)
- [ ] paid version (monthly payment)
    - [ ] no pay per appointment
    - [ ] connect to 1 or more NIP05 (pretty name)

Good to have (future iteration):
- [ ] meet-up like events (NIP52)
    - [ ] of any duration
    - [ ] give it a nice name
    - [ ] set custom cost to join
    - [ ] set extra info (like location)
